
INSERT INTO users (name, email, password, role, status, created_at, updated_at) VALUES
('Alvin Saputra', 'alvin.saputra@example.com', 'hashed_pw_1', 'student', 'active', NOW(), NOW()),
('Dewi Lestari', 'dewi.lestari@example.com', 'hashed_pw_2', 'student', 'active', NOW(), NOW()),
('Rizky Pratama', 'rizky.pratama@example.com', 'hashed_pw_3', 'student', 'active', NOW(), NOW()),
('Siti Nurhaliza', 'siti.nurhaliza@example.com', 'hashed_pw_4', 'student', 'inactive', NOW(), NOW()),
('Budi Santoso', 'budi.santoso@example.com', 'hashed_pw_5', 'mentor', 'active', NOW(), NOW()),
('Indah Mawarni', 'indah.mawarni@example.com', 'hashed_pw_6', 'student', 'active', NOW(), NOW()),
('Yudi Hartono', 'yudi.hartono@example.com', 'hashed_pw_7', 'mentor', 'active', NOW(), NOW()),
('Laras Wulandari', 'laras.wulandari@example.com', 'hashed_pw_8', 'student', 'banned', NOW(), NOW()),
('Fajar Nugroho', 'fajar.nugroho@example.com', 'hashed_pw_9', 'student', 'active', NOW(), NOW()),
('Nina Rahmawati', 'nina.rahmawati@example.com', 'hashed_pw_10', 'mentor', 'active', NOW(), NOW()),
('Bagus Setiawan', 'bagus.setiawan@example.com', 'hashed_pw_11', 'student', 'active', NOW(), NOW()),
('Rina Saraswati', 'rina.saraswati@example.com', 'hashed_pw_12', 'student', 'inactive', NOW(), NOW()),
('Ahmad Fauzan', 'ahmad.fauzan@example.com', 'hashed_pw_13', 'student', 'active', NOW(), NOW()),
('Kirana Putri', 'kirana.putri@example.com', 'hashed_pw_14', 'student', 'active', NOW(), NOW()),
('Dimas Ramadhan', 'dimas.ramadhan@example.com', 'hashed_pw_15', 'mentor', 'active', NOW(), NOW()),
('Mega Sari', 'mega.sari@example.com', 'hashed_pw_16', 'student', 'active', NOW(), NOW()),
('Reza Firmansyah', 'reza.firmansyah@example.com', 'hashed_pw_17', 'student', 'active', NOW(), NOW()),
('Anisa Widya', 'anisa.widya@example.com', 'hashed_pw_18', 'student', 'active', NOW(), NOW()),
('Tomo Wibisono', 'tomo.wibisono@example.com', 'hashed_pw_19', 'admin', 'active', NOW(), NOW()),
('Selvi Anggraini', 'selvi.anggraini@example.com', 'hashed_pw_20', 'student', 'active', NOW(), NOW());

-- Tambahan user agar student_id 21-40 valid
INSERT INTO users (name, email, password, role, status, created_at, updated_at) VALUES
('Rendra Wijaya', 'rendra.wijaya@example.com', 'hashed_pw_21', 'student', 'active', NOW(), NOW()),
('Putri Maharani', 'putri.maharani@example.com', 'hashed_pw_22', 'student', 'active', NOW(), NOW()),
('Arman Kusuma', 'arman.kusuma@example.com', 'hashed_pw_23', 'student', 'active', NOW(), NOW()),
('Bella Kartika', 'bella.kartika@example.com', 'hashed_pw_24', 'student', 'active', NOW(), NOW()),
('Faisal Rahman', 'faisal.rahman@example.com', 'hashed_pw_25', 'student', 'active', NOW(), NOW()),
('Hanif Saputra', 'hanif.saputra@example.com', 'hashed_pw_26', 'student', 'active', NOW(), NOW()),
('Intan Cendana', 'intan.cendana@example.com', 'hashed_pw_27', 'student', 'inactive', NOW(), NOW()),
('Johan Lesmana', 'johan.lesmana@example.com', 'hashed_pw_28', 'student', 'active', NOW(), NOW()),
('Kezia Prameswari', 'kezia.prameswari@example.com', 'hashed_pw_29', 'student', 'active', NOW(), NOW()),
('Lucky Hartawan', 'lucky.hartawan@example.com', 'hashed_pw_30', 'student', 'active', NOW(), NOW()),
('Mita Salsabila', 'mita.salsabila@example.com', 'hashed_pw_31', 'student', 'active', NOW(), NOW()),
('Naufal Adriansyah', 'naufal.adriansyah@example.com', 'hashed_pw_32', 'student', 'active', NOW(), NOW()),
('Olivia Nathania', 'olivia.nathania@example.com', 'hashed_pw_33', 'student', 'active', NOW(), NOW()),
('Pratama Aditya', 'pratama.aditya@example.com', 'hashed_pw_34', 'student', 'active', NOW(), NOW()),
('Qori Ramadhani', 'qori.ramadhani@example.com', 'hashed_pw_35', 'student', 'active', NOW(), NOW()),
('Rika Melati', 'rika.melati@example.com', 'hashed_pw_36', 'student', 'inactive', NOW(), NOW()),
('Steven Gunawan', 'steven.gunawan@example.com', 'hashed_pw_37', 'student', 'active', NOW(), NOW()),
('Tania Kusnadi', 'tania.kusnadi@example.com', 'hashed_pw_38', 'student', 'active', NOW(), NOW()),
('Umar Fauzi', 'umar.fauzi@example.com', 'hashed_pw_39', 'student', 'active', NOW(), NOW()),
('Vania Putri', 'vania.putri@example.com', 'hashed_pw_40', 'student', 'active', NOW(), NOW());

INSERT INTO classrooms (name, description, created_at, updated_at) VALUES
('Pemrograman Dasar', 'Kelas pengenalan dasar pemrograman.', NOW(), NOW()),
('Basis Data Lanjut', 'Materi relasi, indexing, optimasi query.', NOW(), NOW()),
('Jaringan Komputer', 'Belajar protokol dan konfigurasi jaringan.', NOW(), NOW()),
('Algoritma & Struktur Data', 'Belajar algoritma dan struktur data.', NOW(), NOW()),
('Pemrograman Web', 'HTML, CSS, JavaScript, dan backend.', NOW(), NOW()),
('Machine Learning Dasar', 'Pengenalan ML, model, dataset.', NOW(), NOW()),
('Mobile Development', 'Belajar membuat aplikasi Android.', NOW(), NOW()),
('Cloud Computing', 'Dasar cloud, deployment, dan CI/CD.', NOW(), NOW()),
('DevOps Fundamental', 'Konsep CI/CD, Docker, Kubernetes.', NOW(), NOW()),
('Sistem Operasi', 'Proses, memori, filesystem, scheduling.', NOW(), NOW()),
('Keamanan Siber', 'Basic security, cryptography, pentest.', NOW(), NOW()),
('UI/UX Design', 'Wireframe, prototyping, design thinking.', NOW(), NOW()),
('Data Visualization', 'Dashboard, charting, BI tools.', NOW(), NOW()),
('Data Mining', 'Teknik ekstraksi data.', NOW(), NOW()),
('Pemrograman Python', 'Python basic hingga OOP.', NOW(), NOW()),
('Pemrograman Golang', 'Belajar Go lang dari dasar.', NOW(), NOW()),
('Analisis Sistem', 'Menganalisis kebutuhan dan desain sistem.', NOW(), NOW()),
('Artificial Intelligence', 'Pengenalan AI dan aplikasinya.', NOW(), NOW()),
('Pemrograman Java', 'Belajar Java dasar hingga OOP.', NOW(), NOW()),
('Manajemen Proyek TI', 'Project planning, scrum, agile.', NOW(), NOW());

INSERT INTO classroom_mentors (classroom_id, mentor_id, created_at, updated_at) VALUES
(1, 5, NOW(), NOW()),
(2, 7, NOW(), NOW()),
(3, 10, NOW(), NOW()),
(4, 15, NOW(), NOW()),
(5, 5, NOW(), NOW()),
(6, 7, NOW(), NOW()),
(7, 10, NOW(), NOW()),
(8, 15, NOW(), NOW()),
(9, 5, NOW(), NOW()),
(10, 7, NOW(), NOW()),
(11, 10, NOW(), NOW()),
(12, 15, NOW(), NOW()),
(13, 5, NOW(), NOW()),
(14, 7, NOW(), NOW()),
(15, 10, NOW(), NOW()),
(16, 15, NOW(), NOW()),
(17, 5, NOW(), NOW()),
(18, 7, NOW(), NOW()),
(19, 10, NOW(), NOW()),
(20, 15, NOW(), NOW());

INSERT INTO classroom_students (classroom_id, student_id, created_at, updated_at) VALUES
(1, 1, NOW(), NOW()),
(1, 2, NOW(), NOW()),
(2, 3, NOW(), NOW()),
(2, 6, NOW(), NOW()),
(3, 8, NOW(), NOW()),
(3, 9, NOW(), NOW()),
(4, 11, NOW(), NOW()),
(4, 12, NOW(), NOW()),
(5, 13, NOW(), NOW()),
(5, 14, NOW(), NOW()),
(6, 16, NOW(), NOW()),
(6, 17, NOW(), NOW()),
(7, 18, NOW(), NOW()),
(7, 20, NOW(), NOW()),
(8, 1, NOW(), NOW()),
(9, 2, NOW(), NOW()),
(10, 3, NOW(), NOW()),
(10, 6, NOW(), NOW()),
(11, 8, NOW(), NOW()),
(12, 9, NOW(), NOW());

INSERT INTO schedules (classroom_id, start_time, end_time, topic, created_at, updated_at) VALUES
(1, '2024-01-10 09:00', '2024-01-10 11:00', 'Pengenalan Variabel & Tipe Data', NOW(), NOW()),
(1, '2024-01-17 09:00', '2024-01-17 11:00', 'Percabangan & Perulangan', NOW(), NOW()),
(2, '2024-02-05 13:00', '2024-02-05 15:00', 'Relasi dan Kunci Asing', NOW(), NOW()),
(2, '2024-02-12 13:00', '2024-02-12 15:00', 'Index & Query Optimization', NOW(), NOW()),
(3, '2024-03-02 08:00', '2024-03-02 10:00', 'Model OSI & TCP/IP', NOW(), NOW()),
(3, '2024-03-09 08:00', '2024-03-09 10:00', 'Routing & Switching', NOW(), NOW()),
(4, '2024-04-11 10:00', '2024-04-11 12:00', 'Struktur Data List & Array', NOW(), NOW()),
(4, '2024-04-18 10:00', '2024-04-18 12:00', 'Stack dan Queue', NOW(), NOW()),
(5, '2024-05-01 14:00', '2024-05-01 16:00', 'HTML5 Fundamental', NOW(), NOW()),
(5, '2024-05-08 14:00', '2024-05-08 16:00', 'CSS Responsive Design', NOW(), NOW()),
(6, '2024-06-03 09:00', '2024-06-03 11:00', 'Pengenalan Machine Learning', NOW(), NOW()),
(6, '2024-06-10 09:00', '2024-06-10 11:00', 'Dataset, Features, and Labels', NOW(), NOW()),
(7, '2024-07-12 15:00', '2024-07-12 17:00', 'Dasar Android Studio', NOW(), NOW()),
(7, '2024-07-19 15:00', '2024-07-19 17:00', 'Activity & Fragment', NOW(), NOW()),
(8, '2024-08-22 09:00', '2024-08-22 11:00', 'Pengenalan Cloud AWS', NOW(), NOW()),
(8, '2024-08-29 09:00', '2024-08-29 11:00', 'EC2 & IAM Basics', NOW(), NOW()),
(9, '2024-09-16 13:00', '2024-09-16 15:00', 'CI/CD Workflow', NOW(), NOW()),
(9, '2024-09-23 13:00', '2024-09-23 15:00', 'Docker Fundamental', NOW(), NOW()),
(10, '2024-10-04 08:00', '2024-10-04 10:00', 'Manajemen Proses OS', NOW(), NOW()),
(10, '2024-10-11 08:00', '2024-10-11 10:00', 'Scheduling Algorithms', NOW(), NOW());

INSERT INTO materials (title, file_url, uploaded_by, created_at, updated_at) VALUES
('Dasar Pemrograman - Modul 1', '/materials/modul1.pdf', 5, NOW(), NOW()),
('Dasar Pemrograman - Modul 2', '/materials/modul2.pdf', 5, NOW(), NOW()),
('Basis Data - Modul Relasi', '/materials/db_relasi.pdf', 7, NOW(), NOW()),
('Basis Data - Indexing', '/materials/db_indexing.pdf', 7, NOW(), NOW()),
('Jaringan - OSI Model', '/materials/osi_model.pdf', 10, NOW(), NOW()),
('Jaringan - Routing Dasar', '/materials/routing_basic.pdf', 10, NOW(), NOW()),
('Struktur Data - Array', '/materials/array.pdf', 15, NOW(), NOW()),
('Struktur Data - Queue', '/materials/queue.pdf', 15, NOW(), NOW()),
('Web Dev - HTML5', '/materials/html5.pdf', 5, NOW(), NOW()),
('Web Dev - CSS Responsive', '/materials/css_responsive.pdf', 5, NOW(), NOW()),
('ML - Pengenalan ML', '/materials/ml_intro.pdf', 7, NOW(), NOW()),
('ML - Dataset', '/materials/dataset.pdf', 7, NOW(), NOW()),
('Android - Activity', '/materials/activity_module.pdf', 10, NOW(), NOW()),
('Android - Fragment', '/materials/fragment_module.pdf', 10, NOW(), NOW()),
('Cloud - AWS Intro', '/materials/aws_intro.pdf', 15, NOW(), NOW()),
('Cloud - EC2', '/materials/aws_ec2.pdf', 15, NOW(), NOW()),
('DevOps - CI/CD', '/materials/cicd.pdf', 5, NOW(), NOW()),
('DevOps - Docker', '/materials/docker.pdf', 7, NOW(), NOW()),
('Sistem Operasi - Proses', '/materials/os_process.pdf', 10, NOW(), NOW()),
('Sistem Operasi - Filesystem', '/materials/os_filesystem.pdf', 15, NOW(), NOW());

INSERT INTO materials (title, file_url, uploaded_by, created_at, updated_at) VALUES
('Pengantar HTML', 'https://cdn.example.com/materials/html.pdf', 5, NOW(), NOW()),
('Dasar CSS', 'https://cdn.example.com/materials/css.pdf', 6, NOW(), NOW()),
('JavaScript ES6', 'https://cdn.example.com/materials/js.pdf', 7, NOW(), NOW()),
('Struktur Data Array', 'https://cdn.example.com/materials/array.pdf', 8, NOW(), NOW()),
('Struktur Data Linked List', 'https://cdn.example.com/materials/linkedlist.pdf', 9, NOW(), NOW()),
('Algoritma Sorting', 'https://cdn.example.com/materials/sorting.pdf', 10, NOW(), NOW()),
('SQL Fundamental', 'https://cdn.example.com/materials/sql.pdf', 11, NOW(), NOW()),
('ERD & Relational Model', 'https://cdn.example.com/materials/erd.pdf', 12, NOW(), NOW()),
('Pengantar Jaringan', 'https://cdn.example.com/materials/network.pdf', 13, NOW(), NOW()),
('Komunikasi Data', 'https://cdn.example.com/materials/datacom.pdf', 14, NOW(), NOW()),
('OOP dalam Java', 'https://cdn.example.com/materials/oop-java.pdf', 15, NOW(), NOW()),
('Pengenalan Laravel', 'https://cdn.example.com/materials/laravel.pdf', 16, NOW(), NOW()),
('REST API Dasar', 'https://cdn.example.com/materials/rest-api.pdf', 5, NOW(), NOW()),
('JSON & XML', 'https://cdn.example.com/materials/json-xml.pdf', 6, NOW(), NOW()),
('Docker Basic', 'https://cdn.example.com/materials/docker.pdf', 7, NOW(), NOW()),
('CI/CD Pipeline', 'https://cdn.example.com/materials/cicd.pdf', 8, NOW(), NOW()),
('UI/UX Principles', 'https://cdn.example.com/materials/uiux.pdf', 9, NOW(), NOW()),
('Git & GitHub Workflow', 'https://cdn.example.com/materials/git.pdf', 10, NOW(), NOW()),
('Cybersecurity Dasar', 'https://cdn.example.com/materials/cyber.pdf', 11, NOW(), NOW()),
('Cloud Computing Intro', 'https://cdn.example.com/materials/cloud.pdf', 12, NOW(), NOW());

INSERT INTO material_classrooms (material_id, classroom_id, created_at) VALUES
(21, 1, NOW()),
(22, 1, NOW()),
(23, 2, NOW()),
(24, 2, NOW()),
(25, 3, NOW()),
(26, 3, NOW()),
(27, 4, NOW()),
(28, 4, NOW()),
(29, 5, NOW()),
(30, 5, NOW()),
(31, 6, NOW()),
(32, 6, NOW()),
(33, 7, NOW()),
(34, 7, NOW()),
(35, 8, NOW()),
(36, 8, NOW()),
(37, 9, NOW()),
(38, 9, NOW()),
(39, 10, NOW()),
(40, 10, NOW());

INSERT INTO schedules (classroom_id, start_time, end_time, topic, created_at, updated_at) VALUES
(1, '2025-01-10 09:00', '2025-01-10 11:00', 'HTML Dasar', NOW(), NOW()),
(1, '2025-01-12 13:00', '2025-01-12 15:00', 'CSS Dasar', NOW(), NOW()),
(2, '2025-01-14 09:00', '2025-01-14 11:00', 'JavaScript ES6', NOW(), NOW()),
(2, '2025-01-16 13:00', '2025-01-16 15:00', 'DOM Manipulation', NOW(), NOW()),
(3, '2025-01-18 09:00', '2025-01-18 11:00', 'Array & List', NOW(), NOW()),
(3, '2025-01-20 13:00', '2025-01-20 15:00', 'Stack & Queue', NOW(), NOW()),
(4, '2025-01-21 09:00', '2025-01-21 11:00', 'Pengantar Jaringan', NOW(), NOW()),
(4, '2025-01-22 13:00', '2025-01-22 15:00', 'TCP/IP Model', NOW(), NOW()),
(5, '2025-01-23 09:00', '2025-01-23 11:00', 'OOP Fundamentals', NOW(), NOW()),
(5, '2025-01-24 13:00', '2025-01-24 15:00', 'Encapsulation', NOW(), NOW()),
(6, '2025-01-25 09:00', '2025-01-25 11:00', 'Laravel Routing', NOW(), NOW()),
(6, '2025-01-26 13:00', '2025-01-26 15:00', 'Laravel Controller', NOW(), NOW()),
(7, '2025-01-27 09:00', '2025-01-27 11:00', 'API Development', NOW(), NOW()),
(7, '2025-01-28 13:00', '2025-01-28 15:00', 'JSON Handling', NOW(), NOW()),
(8, '2025-01-29 09:00', '2025-01-29 11:00', 'Docker Intro', NOW(), NOW()),
(8, '2025-01-30 13:00', '2025-01-30 15:00', 'Docker Compose', NOW(), NOW()),
(9, '2025-01-31 09:00', '2025-01-31 11:00', 'UI/UX Basics', NOW(), NOW()),
(9, '2025-02-01 13:00', '2025-02-01 15:00', 'Wireframing', NOW(), NOW()),
(10, '2025-02-02 09:00', '2025-02-02 11:00', 'Cybersecurity Intro', NOW(), NOW()),
(10, '2025-02-03 13:00', '2025-02-03 15:00', 'Cloud Concepts', NOW(), NOW());

INSERT INTO classroom_students (classroom_id, student_id, created_at, updated_at) VALUES
(1, 21, NOW(), NOW()),
(1, 22, NOW(), NOW()),
(2, 23, NOW(), NOW()),
(2, 24, NOW(), NOW()),
(3, 25, NOW(), NOW()),
(3, 26, NOW(), NOW()),
(4, 27, NOW(), NOW()),
(4, 28, NOW(), NOW()),
(5, 29, NOW(), NOW()),
(5, 30, NOW(), NOW()),
(6, 31, NOW(), NOW()),
(6, 32, NOW(), NOW()),
(7, 33, NOW(), NOW()),
(7, 34, NOW(), NOW()),
(8, 35, NOW(), NOW()),
(8, 36, NOW(), NOW()),
(9, 37, NOW(), NOW()),
(9, 38, NOW(), NOW()),
(10, 39, NOW(), NOW()),
(10, 40, NOW(), NOW());

INSERT INTO classroom_mentors (classroom_id, mentor_id, created_at, updated_at) VALUES
(1, 5, NOW(), NOW()),
(2, 6, NOW(), NOW()),
(3, 7, NOW(), NOW()),
(4, 8, NOW(), NOW()),
(5, 9, NOW(), NOW()),
(6, 10, NOW(), NOW()),
(7, 11, NOW(), NOW()),
(8, 12, NOW(), NOW()),
(9, 13, NOW(), NOW()),
(10, 14, NOW(), NOW()),
(1, 15, NOW(), NOW()),
(2, 16, NOW(), NOW()),
(3, 17, NOW(), NOW()),
(4, 18, NOW(), NOW()),
(5, 19, NOW(), NOW()),
(6, 20, NOW(), NOW()),
(7, 5, NOW(), NOW()),
(8, 6, NOW(), NOW()),
(9, 7, NOW(), NOW()),
(10, 8, NOW(), NOW());

INSERT INTO assignments (classroom_id, title, description, file_url, deadline, created_by, created_at, updated_at) VALUES
(1, 'Tugas HTML Dasar', 'Buat struktur HTML lengkap dengan semantic tag.', 'https://cdn.example.com/assign/html1.pdf', '2025-01-15 23:59', 5, NOW(), NOW()),
(1, 'Tugas CSS Layout', 'Buat layout website menggunakan Flexbox.', 'https://cdn.example.com/assign/css1.pdf', '2025-01-18 23:59', 6, NOW(), NOW()),
(2, 'Tugas JS ES6', 'Implementasi let, const dan arrow function.', 'https://cdn.example.com/assign/js1.pdf', '2025-01-20 23:59', 7, NOW(), NOW()),
(2, 'DOM Manipulation', 'Buat galeri gambar dengan DOM.', 'https://cdn.example.com/assign/dom1.pdf', '2025-01-22 23:59', 8, NOW(), NOW()),
(3, 'Tugas Struktur Data', 'Implementasi array dan linked list.', 'https://cdn.example.com/assign/sd1.pdf', '2025-01-24 23:59', 9, NOW(), NOW()),
(3, 'Stack & Queue', 'Buat stack dan queue dengan JS.', 'https://cdn.example.com/assign/stack1.pdf', '2025-01-26 23:59', 10, NOW(), NOW()),
(4, 'Jaringan Dasar', 'Jelaskan OSI layer secara detail.', 'https://cdn.example.com/assign/network1.pdf', '2025-01-27 23:59', 11, NOW(), NOW()),
(4, 'TCP/IP Model', 'Buat rangkuman layer TCP/IP.', 'https://cdn.example.com/assign/tcp1.pdf', '2025-01-29 23:59', 12, NOW(), NOW()),
(5, 'OOP Fundamental', 'Implementasi Class, Object & Method.', 'https://cdn.example.com/assign/oop1.pdf', '2025-01-30 23:59', 13, NOW(), NOW()),
(5, 'Encapsulation', 'Buat contoh encapsulation dalam Java.', 'https://cdn.example.com/assign/encap1.pdf', '2025-02-01 23:59', 14, NOW(), NOW()),
(6, 'Laravel Routing', 'Buat route CRUD sederhana.', 'https://cdn.example.com/assign/laravel1.pdf', '2025-02-02 23:59', 15, NOW(), NOW()),
(6, 'Laravel Controller', 'Buat controller dengan resource.', 'https://cdn.example.com/assign/laravel2.pdf', '2025-02-04 23:59', 16, NOW(), NOW()),
(7, 'REST API', 'Buat API untuk CRUD artikel.', 'https://cdn.example.com/assign/api1.pdf', '2025-02-05 23:59', 17, NOW(), NOW()),
(7, 'JSON Handling', 'Parsing JSON client & server.', 'https://cdn.example.com/assign/json1.pdf', '2025-02-07 23:59', 18, NOW(), NOW()),
(8, 'Docker Image', 'Build docker image sederhana.', 'https://cdn.example.com/assign/docker1.pdf', '2025-02-08 23:59', 19, NOW(), NOW()),
(8, 'Docker Compose', 'Setup microservice dengan compose.', 'https://cdn.example.com/assign/compose1.pdf', '2025-02-10 23:59', 20, NOW(), NOW()),
(9, 'UI/UX Riset', 'Analisis kebutuhan user.', 'https://cdn.example.com/assign/uiux1.pdf', '2025-02-11 23:59', 5, NOW(), NOW()),
(9, 'Wireframing', 'Buat wireframe aplikasi kasir.', 'https://cdn.example.com/assign/wire1.pdf', '2025-02-13 23:59', 6, NOW(), NOW()),
(10, 'Cybersecurity Intro', 'Riset ancaman siber modern.', 'https://cdn.example.com/assign/cyber1.pdf', '2025-02-14 23:59', 7, NOW(), NOW()),
(10, 'Cloud Concepts', 'Deskripsikan layanan IaaS, PaaS, SaaS.', 'https://cdn.example.com/assign/cloud1.pdf', '2025-02-16 23:59', 8, NOW(), NOW());

INSERT INTO assignment_submissions (assignment_id, student_id, file_url, created_at, updated_at) VALUES
(1, 21, 'https://cdn.example.com/submission/html21.zip', NOW(), NOW()),
(1, 22, 'https://cdn.example.com/submission/html22.zip', NOW(), NOW()),
(2, 21, 'https://cdn.example.com/submission/css21.zip', NOW(), NOW()),
(2, 22, 'https://cdn.example.com/submission/css22.zip', NOW(), NOW()),
(3, 23, 'https://cdn.example.com/submission/js23.zip', NOW(), NOW()),
(3, 24, 'https://cdn.example.com/submission/js24.zip', NOW(), NOW()),
(4, 23, 'https://cdn.example.com/submission/dom23.zip', NOW(), NOW()),
(4, 24, 'https://cdn.example.com/submission/dom24.zip', NOW(), NOW()),
(5, 25, 'https://cdn.example.com/submission/sd25.zip', NOW(), NOW()),
(5, 26, 'https://cdn.example.com/submission/sd26.zip', NOW(), NOW()),
(6, 25, 'https://cdn.example.com/submission/stack25.zip', NOW(), NOW()),
(6, 26, 'https://cdn.example.com/submission/stack26.zip', NOW(), NOW()),
(7, 27, 'https://cdn.example.com/submission/osi27.zip', NOW(), NOW()),
(7, 28, 'https://cdn.example.com/submission/osi28.zip', NOW(), NOW()),
(8, 27, 'https://cdn.example.com/submission/tcp27.zip', NOW(), NOW()),
(8, 28, 'https://cdn.example.com/submission/tcp28.zip', NOW(), NOW()),
(9, 29, 'https://cdn.example.com/submission/oop29.zip', NOW(), NOW()),
(9, 30, 'https://cdn.example.com/submission/oop30.zip', NOW(), NOW()),
(10, 29, 'https://cdn.example.com/submission/encap29.zip', NOW(), NOW()),
(10, 30, 'https://cdn.example.com/submission/encap30.zip', NOW(), NOW());

INSERT INTO grades (student_id, assignment_id, grade, feedback, graded_by, graded_at, updated_at) VALUES
(21, 1, 90, 'Struktur HTML sudah rapi.', 5, NOW(), NOW()),
(22, 1, 85, 'Bagus, hanya kurang semantic.', 5, NOW(), NOW()),
(21, 2, 88, 'Layout flexbox bagus.', 6, NOW(), NOW()),
(22, 2, 92, 'Sangat baik.', 6, NOW(), NOW()),
(23, 3, 87, 'Arrow function sudah benar.', 7, NOW(), NOW()),
(24, 3, 80, 'Perlu perbaikan pada const.', 7, NOW(), NOW()),
(23, 4, 90, 'DOM lengkap dan interaktif.', 8, NOW(), NOW()),
(24, 4, 84, 'Kurang validasi input.', 8, NOW(), NOW()),
(25, 5, 89, 'Linked list berjalan baik.', 9, NOW(), NOW()),
(26, 5, 86, 'Array manipulasi benar.', 9, NOW(), NOW()),
(25, 6, 91, 'Stack & queue berhasil.', 10, NOW(), NOW()),
(26, 6, 83, 'Queue kurang lengkap.', 10, NOW(), NOW()),
(27, 7, 90, 'OSI layer lengkap.', 11, NOW(), NOW()),
(28, 7, 82, 'Kurang ringkas.', 11, NOW(), NOW()),
(27, 8, 88, 'TCP/IP akurat.', 12, NOW(), NOW()),
(28, 8, 85, 'Cukup baik.', 12, NOW(), NOW()),
(29, 9, 92, 'OOP sangat baik.', 13, NOW(), NOW()),
(30, 9, 89, 'Sudah sesuai konsep.', 13, NOW(), NOW()),
(29, 10, 94, 'Enkapsulasi kuat.', 14, NOW(), NOW()),
(30, 10, 88, 'Bagus namun kurang dokumentasi.', 14, NOW(), NOW());

INSERT INTO announcements (classroom_id, created_by, title, message, created_at, updated_at) VALUES
(1, 5, 'Pengumuman Kelas HTML', 'Kelas besok dimulai pukul 09.00 WIB.', NOW(), NOW()),
(1, 6, 'Materi CSS Telah Diunggah', 'Silakan cek materi terbaru di menu Materials.', NOW(), NOW()),
(2, 7, 'Kuis JavaScript', 'Kuis akan dibuka pada 20 Januari 2025.', NOW(), NOW()),
(2, 8, 'Update Jadwal', 'Jadwal coding practice dimajukan 1 jam.', NOW(), NOW()),
(3, 9, 'Tugas Struktur Data', 'Pastikan upload sebelum deadline.', NOW(), NOW()),
(3, 10, 'Review Mingguan', 'Akan ada evaluasi progress.', NOW(), NOW()),
(4, 11, 'Praktikum Jaringan', 'Bawa laptop untuk simulasi jaringan.', NOW(), NOW()),
(4, 12, 'Perubahan Jadwal Lab', 'Lab jaringan dipindah ke hari Jumat.', NOW(), NOW()),
(5, 13, 'Pertemuan OOP', 'Materi OOP lanjutan minggu depan.', NOW(), NOW()),
(5, 14, 'Reminder Tugas OOP', 'Jangan lupa kirim tugas sebelum deadline.', NOW(), NOW()),
(6, 15, 'Laravel Migration', 'Gunakan migration untuk struktur database.', NOW(), NOW()),
(6, 16, 'Live Coding Laravel', 'Akan dilakukan sesi zoom.', NOW(), NOW()),
(7, 17, 'REST API Debugging', 'Sesi debugging bersama.', NOW(), NOW()),
(7, 18, 'Postman Collection', 'Sudah diupload ke materials.', NOW(), NOW()),
(8, 19, 'Docker Class', 'Pastikan sudah install Docker Desktop.', NOW(), NOW()),
(8, 20, 'Compose Update', 'File compose terbaru tersedia.', NOW(), NOW()),
(9, 5, 'UI/UX Diskusi', 'Kita bahas user flow aplikasi kasir.', NOW(), NOW()),
(9, 6, 'Wireframe Assignment', 'Upload wireframe ke Google Drive.', NOW(), NOW()),
(10, 7, 'Cybersecurity Awareness', 'Waspadai phishing email.', NOW(), NOW()),
(10, 8, 'Cloud Basics', 'Materi cloud sudah ditambahkan.', NOW(), NOW());

-- Thread utama diskusi (parent_id NULL)
INSERT INTO discussions (classroom_id, user_id, parent_id, content, created_at, updated_at) VALUES
(1, 21, NULL, 'Saya kesulitan memahami semantic HTML.', NOW(), NOW()),
(2, 23, NULL, 'Kapan kuis JS dibuka?', NOW(), NOW()),
(3, 25, NULL, 'Linked list masih membingungkan.', NOW(), NOW()),
(4, 27, NULL, 'Apakah perlu install Wireshark?', NOW(), NOW()),
(5, 29, NULL, 'Perbedaan inheritance dan polymorphism?', NOW(), NOW()),
(6, 31, NULL, 'Resource controller untuk apa?', NOW(), NOW()),
(7, 33, NULL, 'Error saat fetch API.', NOW(), NOW()),
(8, 35, NULL, 'Docker Compose tidak jalan.', NOW(), NOW()),
(9, 37, NULL, 'User flow terlalu panjang.', NOW(), NOW()),
(10, 39, NULL, 'Apa itu phishing?', NOW(), NOW());

-- Balasan diskusi menggunakan parent_id dari thread di atas
INSERT INTO discussions (classroom_id, user_id, parent_id, content, created_at, updated_at) VALUES
(1, 5, (SELECT id FROM discussions WHERE content = 'Saya kesulitan memahami semantic HTML.'), 'Coba pelajari tag section, article, nav.', NOW(), NOW()),
(2, 7, (SELECT id FROM discussions WHERE content = 'Kapan kuis JS dibuka?'), 'Kuis dibuka tanggal 20 Januari.', NOW(), NOW()),
(3, 9, (SELECT id FROM discussions WHERE content = 'Linked list masih membingungkan.'), 'Saya akan kirim contoh implementasi.', NOW(), NOW()),
(4, 11, (SELECT id FROM discussions WHERE content = 'Apakah perlu install Wireshark?'), 'Ya, sangat disarankan.', NOW(), NOW()),
(5, 13, (SELECT id FROM discussions WHERE content = 'Perbedaan inheritance dan polymorphism?'), 'Polymorphism fokus pada behavior.', NOW(), NOW()),
(6, 15, (SELECT id FROM discussions WHERE content = 'Resource controller untuk apa?'), 'Untuk CRUD dengan struktur rapi.', NOW(), NOW()),
(7, 17, (SELECT id FROM discussions WHERE content = 'Error saat fetch API.'), 'Coba cek header request.', NOW(), NOW()),
(8, 19, (SELECT id FROM discussions WHERE content = 'Docker Compose tidak jalan.'), 'Pastikan versi docker terbaru.', NOW(), NOW()),
(9, 5, (SELECT id FROM discussions WHERE content = 'User flow terlalu panjang.'), 'Coba sederhanakan step registrasi.', NOW(), NOW()),
(10, 7, (SELECT id FROM discussions WHERE content = 'Apa itu phishing?'), 'Phishing adalah penipuan lewat email.', NOW(), NOW());

INSERT INTO notifications (user_id, announcement_id, discussion_id, title, message, is_read, created_at, updated_at) VALUES
(21, (SELECT id FROM announcements WHERE title = 'Pengumuman Kelas HTML'), NULL, 'Pengumuman Baru', 'Kelas HTML dimulai 09.00 WIB.', false, NOW(), NOW()),
(22, (SELECT id FROM announcements WHERE title = 'Pengumuman Kelas HTML'), NULL, 'Pengumuman Baru', 'Kelas HTML dimulai 09.00 WIB.', false, NOW(), NOW()),
(23, (SELECT id FROM announcements WHERE title = 'Kuis JavaScript'), NULL, 'Kuis JS', 'Kuis JS akan dibuka.', false, NOW(), NOW()),
(24, (SELECT id FROM announcements WHERE title = 'Kuis JavaScript'), NULL, 'Kuis JS', 'Kuis JS akan dibuka.', false, NOW(), NOW()),
(25, (SELECT id FROM announcements WHERE title = 'Tugas Struktur Data'), NULL, 'Tugas Struktur Data', 'Jangan lewatkan deadline.', false, NOW(), NOW()),
(26, (SELECT id FROM announcements WHERE title = 'Tugas Struktur Data'), NULL, 'Tugas Struktur Data', 'Jangan lewatkan deadline.', false, NOW(), NOW()),
(27, (SELECT id FROM announcements WHERE title = 'Praktikum Jaringan'), NULL, 'Praktikum Jaringan', 'Bawa laptop ya besok.', false, NOW(), NOW()),
(28, (SELECT id FROM announcements WHERE title = 'Praktikum Jaringan'), NULL, 'Praktikum Jaringan', 'Bawa laptop ya besok.', false, NOW(), NOW()),
(29, (SELECT id FROM announcements WHERE title = 'Pertemuan OOP'), NULL, 'Pertemuan OOP', 'Materi OOP minggu depan.', false, NOW(), NOW()),
(30, (SELECT id FROM announcements WHERE title = 'Pertemuan OOP'), NULL, 'Pertemuan OOP', 'Materi OOP minggu depan.', false, NOW(), NOW()),
(31, (SELECT id FROM announcements WHERE title = 'Laravel Migration'), NULL, 'Laravel Migration', 'Gunakan migration.', false, NOW(), NOW()),
(32, (SELECT id FROM announcements WHERE title = 'Laravel Migration'), NULL, 'Laravel Migration', 'Gunakan migration.', false, NOW(), NOW()),
(33, (SELECT id FROM announcements WHERE title = 'REST API Debugging'), NULL, 'API Debugging', 'Sesi debugging dimulai.', false, NOW(), NOW()),
(34, (SELECT id FROM announcements WHERE title = 'REST API Debugging'), NULL, 'API Debugging', 'Sesi debugging dimulai.', false, NOW(), NOW()),
(35, (SELECT id FROM announcements WHERE title = 'Docker Class'), NULL, 'Docker Class', 'Install Docker Desktop.', false, NOW(), NOW()),
(36, (SELECT id FROM announcements WHERE title = 'Docker Class'), NULL, 'Docker Class', 'Install Docker Desktop.', false, NOW(), NOW()),
(37, (SELECT id FROM announcements WHERE title = 'UI/UX Diskusi'), NULL, 'UI/UX Diskusi', 'Coba sederhanakan user flow.', false, NOW(), NOW()),
(38, (SELECT id FROM announcements WHERE title = 'UI/UX Diskusi'), NULL, 'UI/UX Diskusi', 'Coba sederhanakan user flow.', false, NOW(), NOW()),
(39, (SELECT id FROM announcements WHERE title = 'Cybersecurity Awareness'), NULL, 'Cybersecurity Alert', 'Hati-hati phishing.', false, NOW(), NOW()),
(40, (SELECT id FROM announcements WHERE title = 'Cybersecurity Awareness'), NULL, 'Cybersecurity Alert', 'Hati-hati phishing.', false, NOW(), NOW());

INSERT INTO feedbacks (from_user_id, to_user_id, classroom_id, rating, comment, created_at)
VALUES
(5, 21, 1, 5, 'Sudah bagus, terus tingkatkan.', NOW()),
(2, 22, 1, 4, 'Perlu lebih rapi.', NOW()),
(7, 23, 2, 5, 'Logika JS kamu kuat.', NOW()),
(8, 24, 2, 4, 'Masih perlu latihan DOM.', NOW()),
(9, 25, 3, 5, 'Struktur data kamu bagus.', NOW()),
(10, 26, 3, 4, 'Sedikit kurang rapi.', NOW()),
(11, 27, 4, 5, 'Analisis jaringan bagus.', NOW()),
(12, 28, 4, 4, 'Perlu review OSI lagi.', NOW()),
(13, 29, 5, 5, 'OOP kamu mantap.', NOW()),
(14, 30, 5, 4, 'Perbaiki dokumentasi.', NOW()),
(15, 31, 6, 5, 'Laravel routing bagus.', NOW()),
(16, 32, 6, 4, 'Cek kembali middleware.', NOW()),
(17, 33, 7, 5, 'API clean dan easy to read.', NOW()),
(18, 34, 7, 4, 'Kurang validasi input.', NOW()),
(19, 35, 8, 5, 'Docker compose berjalan baik.', NOW()),
(20, 36, 8, 4, 'Perlu optimize container.', NOW()),
(5, 37, 9, 5, 'UI/UX kamu matang.', NOW()),
(2, 38, 9, 4, 'Wireframe perlu grid layout.', NOW()),
(7, 39, 10, 5, 'Pengetahuan cybersecurity bagus.', NOW()),
(8, 40, 10, 4, 'Kurangi teks panjang di presentasi.', NOW());

INSERT INTO attendances (schedule_id, user_id, status, checked_at, updated_at) VALUES
(1, 21, 'present', NOW(), NOW()),
(2, 22, 'present', NOW(), NOW()),
(3, 23, 'late', NOW(), NOW()),
(4, 24, 'present', NOW(), NOW()),
(5, 25, 'absent', NOW(), NOW()),
(6, 26, 'present', NOW(), NOW()),
(7, 27, 'present', NOW(), NOW()),
(8, 28, 'late', NOW(), NOW()),
(9, 29, 'present', NOW(), NOW()),
(10, 30, 'present', NOW(), NOW()),
(11, 31, 'present', NOW(), NOW()),
(12, 32, 'absent', NOW(), NOW()),
(13, 33, 'present', NOW(), NOW()),
(14, 34, 'present', NOW(), NOW()),
(15, 35, 'late', NOW(), NOW()),
(16, 36, 'present', NOW(), NOW()),
(17, 37, 'present', NOW(), NOW()),
(18, 38, 'present', NOW(), NOW()),
(19, 39, 'present', NOW(), NOW()),
(20, 40, 'absent', NOW(), NOW());

INSERT INTO attendances (schedule_id, user_id, status, checked_at, updated_at) VALUES
(1, 1, 'present', NOW(), NOW()),
(2, 2, 'present', NOW(), NOW()),
(1, 3, 'present', NOW(), NOW()),
(2, 4, 'present', NOW(), NOW());